// Package qortoo is the Go binding of the Qortoo CRDT SDK (qortoo-rs).
//
// It links the qortoo-ffi static library built from the same repository:
//
//	cargo build -p qortoo-ffi          # or: make ffi
//	go test ./go/...
//
// Every object returned by this package owns a native handle and must be
// released with its Close method. As a backstop, an unreachable wrapper frees
// its native handle via a runtime.AddCleanup cleanup, but cleanups are not
// guaranteed to run — treat Close as the contract, not the cleanup. A Counter
// keeps its Client reachable, so an otherwise unreferenced Client is not
// cleaned up while any of its counters is still alive.
//
// Close must not be called concurrently with other methods on the same object;
// all other methods are safe for concurrent use.
//
// Handler callbacks (Handler.OnStateChange / Handler.OnError) are invoked on
// Qortoo-owned tokio worker threads, asynchronously to the triggering
// operation. They must be safe for concurrent use and must not block for long.
// A blocking handler also delays Client.Close, which shuts the worker threads
// down, and ShutdownObservability, which flushes the exporters.
//
// The Rust core emits tracing spans and metrics but installs no subscriber,
// recorder, or exporter on its own: call InitObservability once at startup to
// choose where they go, and the *Context methods (Counter.SyncContext,
// Counter.TransactionContext) to keep them in the trace of the calling span.
package qortoo

/*
#cgo CFLAGS: -I${SRCDIR}/../../qortoo-ffi/include
#cgo LDFLAGS: -L${SRCDIR}/../../target/debug -L${SRCDIR}/../../target/release -lqortoo_ffi
#cgo linux LDFLAGS: -lm -ldl -lpthread

#include <stdlib.h>
#include <qortoo.h>

// Prototypes of the Go callback trampolines exported from callbacks.go.
// (Definitions are generated by cgo; //export files must keep their own
// preambles declaration-only, so the fn-pointer getters live here instead.)
extern void goQortooOnStateChange(uintptr_t userdata, int32_t old_state, int32_t new_state);
extern void goQortooOnError(uintptr_t userdata, int32_t code, char *msg);
extern void goQortooUserdataDrop(uintptr_t userdata);
extern int32_t goQortooTxCallback(QortooCounter *tx_counter, uintptr_t userdata);

// Non-static on purpose: cgo preambles are per-file translation units, so these
// must have external linkage to be callable from the other files of this package.
// Casts bridge const-ness differences between the cgo-generated prototypes and
// the callback typedefs.
QortooOnStateChangeCallback qortooGoStateChangeCB(void) {
	return goQortooOnStateChange;
}
QortooOnErrorCallback qortooGoErrorCB(void) {
	return (QortooOnErrorCallback)goQortooOnError;
}
QortooUserdataDropCallback qortooGoUserdataDropCB(void) {
	return goQortooUserdataDrop;
}
QortooTxCallback qortooGoTxCB(void) {
	return goQortooTxCallback;
}
*/
import "C"

import "unsafe"

// goString copies and frees a Rust-owned C string.
func goString(s *C.char) string {
	if s == nil {
		return ""
	}
	defer C.qortoo_string_free(s)
	return C.GoString(s)
}

// cString allocates a C copy of s; the caller must free it.
func cString(s string) *C.char {
	return C.CString(s)
}

func freeCString(s *C.char) {
	C.free(unsafe.Pointer(s))
}
