/* Auto-generated by cbindgen from qortoo-ffi. Do not edit manually. */

#ifndef QORTOO_FFI_H
#define QORTOO_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Error code used when a panic crosses the FFI boundary or an error variant is unknown.
 */
#define QORTOO_ERR_INTERNAL_FFI 999

/**
 * Error code used when an argument (null pointer, invalid UTF-8) is rejected at the boundary.
 */
#define QORTOO_ERR_INVALID_ARGUMENT 998

/**
 * Opaque handle to a `qortoo::Client`.
 */
typedef struct QortooClient QortooClient;

/**
 * Opaque handle to a `qortoo::Counter`. Cheap to clone on the Rust side; every handle
 * shares the same underlying datatype.
 */
typedef struct QortooCounter QortooCounter;

/**
 * Opaque handle to a `qortoo::LocalConnectivity`. The same handle may be passed to
 * several `qortoo_client_new` calls to share one in-memory backend.
 */
typedef struct QortooLocalConnectivity QortooLocalConnectivity;

/**
 * Out-parameter carrying the result of a fallible call.
 */
typedef struct QortooError {
  /**
   * 0 on success; otherwise the Rust error discriminant (or 998/999, see constants).
   */
  int32_t code;
  /**
   * Human-readable message, or null. Release with `qortoo_string_free`.
   */
  char *msg;
} QortooError;

/**
 * State-change notification: `(userdata, old_state, new_state)` with `DatatypeState`
 * discriminants. Invoked on a Qortoo tokio worker thread.
 */
typedef void (*QortooOnStateChangeCallback)(uintptr_t userdata, int32_t old_state, int32_t new_state);

/**
 * Error notification: `(userdata, error_code, error_msg)`. `error_msg` is only valid
 * during the call. Invoked on a Qortoo tokio worker thread.
 */
typedef void (*QortooOnErrorCallback)(uintptr_t userdata, int32_t code, const char *msg);

/**
 * Called exactly once when the handler owning `userdata` is dropped, so the foreign
 * side can release resources tied to it (e.g., a Go `cgo.Handle`).
 */
typedef void (*QortooUserdataDropCallback)(uintptr_t userdata);

/**
 * Options applied when building a datatype. A zeroed struct (or a null pointer where
 * the options parameter is nullable) selects the defaults.
 */
typedef struct QortooDatatypeOptions {
  /**
   * Marks the datatype read-only (`DatatypeBuilder::with_readonly`).
   */
  bool readonly;
  /**
   * Max push-buffer size in bytes; 0 keeps the SDK default (clamped by the SDK).
   */
  uint64_t max_push_buffer_size;
  /**
   * Priority of the handler registered from the fields below (lower runs first).
   */
  uintptr_t handler_priority;
  /**
   * Optional state-change callback; null to skip.
   */
  QortooOnStateChangeCallback on_state_change;
  /**
   * Optional error callback; null to skip.
   */
  QortooOnErrorCallback on_error;
  /**
   * Opaque integer (e.g., a Go `cgo.Handle`) forwarded to both callbacks.
   */
  uintptr_t handler_userdata;
  /**
   * Optional destructor for `handler_userdata`; null to skip.
   */
  QortooUserdataDropCallback handler_userdata_drop;
} QortooDatatypeOptions;

/**
 * Transaction body. Receives a transaction-scoped counter (owned by Rust — do NOT free)
 * and the userdata given to `qortoo_counter_transaction`. Return 0 to commit, non-zero
 * to roll back.
 */
typedef int32_t (*QortooTxCallback)(struct QortooCounter *tx_counter, uintptr_t userdata);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates a client. `connectivity` may be null (no-op backend).
 * Returns null on error (see `err_out`). Release with `qortoo_client_free`.
 */
struct QortooClient *qortoo_client_new(const char *collection,
                                       const char *alias,
                                       const struct QortooLocalConnectivity *connectivity,
                                       struct QortooError *err_out);

/**
 * Releases the client. Datatypes built from it stay valid until their own free.
 */
void qortoo_client_free(struct QortooClient *client);

/**
 * Returns the collection name (release with `qortoo_string_free`).
 */
char *qortoo_client_get_collection(const struct QortooClient *client);

/**
 * Returns the client alias (release with `qortoo_string_free`).
 */
char *qortoo_client_get_alias(const struct QortooClient *client);

/**
 * Marks the datatype identified by `key` as unsubscribing. With manual connectivity a
 * following `qortoo_counter_sync` drives it to Disabled.
 */
void qortoo_client_unsubscribe_datatype(const struct QortooClient *client,
                                        const char *key,
                                        struct QortooError *err_out);

/**
 * Builds a counter in `Creating` state (writable). `options` may be null.
 * The handler `userdata_drop` (if provided) fires exactly once even on failure.
 */
struct QortooCounter *qortoo_counter_create(const struct QortooClient *client,
                                            const char *key,
                                            const struct QortooDatatypeOptions *options,
                                            struct QortooError *err_out);

/**
 * Builds a counter in `Subscribing` state (read-only until synced). `options` may be null.
 * The handler `userdata_drop` (if provided) fires exactly once even on failure.
 */
struct QortooCounter *qortoo_counter_subscribe(const struct QortooClient *client,
                                               const char *key,
                                               const struct QortooDatatypeOptions *options,
                                               struct QortooError *err_out);

/**
 * Builds a counter in `SubscribingOrCreating` state (writable). `options` may be null.
 * The handler `userdata_drop` (if provided) fires exactly once even on failure.
 */
struct QortooCounter *qortoo_counter_subscribe_or_create(const struct QortooClient *client,
                                                         const char *key,
                                                         const struct QortooDatatypeOptions *options,
                                                         struct QortooError *err_out);

/**
 * Releases this counter handle; the underlying datatype lives on inside the client.
 */
void qortoo_counter_free(struct QortooCounter *counter);

/**
 * Increases the counter by `delta` (may be negative). Returns the new value, or 0 on error.
 */
int64_t qortoo_counter_increase_by(const struct QortooCounter *counter,
                                   int64_t delta,
                                   struct QortooError *err_out);

/**
 * Increases the counter by 1. Returns the new value, or 0 on error.
 */
int64_t qortoo_counter_increase(const struct QortooCounter *counter, struct QortooError *err_out);

/**
 * Returns the current counter value (0 if `counter` is null).
 */
int64_t qortoo_counter_get_value(const struct QortooCounter *counter);

/**
 * Blocking push/pull synchronization with the connectivity backend.
 */
void qortoo_counter_sync(const struct QortooCounter *counter, struct QortooError *err_out);

/**
 * Marks this datatype as unsubscribing (see `qortoo_client_unsubscribe_datatype`).
 */
void qortoo_counter_unsubscribe(const struct QortooCounter *counter, struct QortooError *err_out);

/**
 * Returns the `DatatypeState` discriminant, or -1 if `counter` is null.
 */
int32_t qortoo_counter_get_state(const struct QortooCounter *counter);

/**
 * Returns the `DataType` discriminant, or -1 if `counter` is null.
 */
int32_t qortoo_counter_get_type(const struct QortooCounter *counter);

/**
 * Returns the datatype key (release with `qortoo_string_free`).
 */
char *qortoo_counter_get_key(const struct QortooCounter *counter);

/**
 * Returns the server-side version (0 before the first sync or if `counter` is null).
 */
uint64_t qortoo_counter_get_server_version(const struct QortooCounter *counter);

/**
 * Returns the client-side version (number of local operations).
 */
uint64_t qortoo_counter_get_client_version(const struct QortooCounter *counter);

/**
 * Returns the last synchronized client version.
 */
uint64_t qortoo_counter_get_synced_client_version(const struct QortooCounter *counter);

/**
 * Executes `callback` atomically. The callback runs inline on the calling thread with a
 * transaction-scoped counter handle owned by Rust (do NOT free it, do NOT keep it after
 * returning). A non-zero return rolls back every operation performed inside.
 */
void qortoo_counter_transaction(const struct QortooCounter *counter,
                                const char *tag,
                                QortooTxCallback callback,
                                uintptr_t userdata,
                                struct QortooError *err_out);

/**
 * Registers (or replaces) a handler at `priority`. Callbacks arrive on Qortoo tokio
 * worker threads; `userdata_drop` fires exactly once when the handler is replaced or
 * unset — or immediately if `counter` is null and the handler cannot be registered.
 */
void qortoo_counter_set_handler(const struct QortooCounter *counter,
                                uintptr_t priority,
                                QortooOnStateChangeCallback on_state_change,
                                QortooOnErrorCallback on_error,
                                uintptr_t userdata,
                                QortooUserdataDropCallback userdata_drop);

/**
 * Removes the handler at `priority`. Returns true if one was removed.
 */
bool qortoo_counter_unset_handler(const struct QortooCounter *counter, uintptr_t priority);

/**
 * Creates an in-memory connectivity backend (realtime mode by default).
 */
struct QortooLocalConnectivity *qortoo_local_connectivity_new(void);

/**
 * Switches between realtime (true) and manual (false) synchronization.
 */
void qortoo_local_connectivity_set_realtime(struct QortooLocalConnectivity *conn, bool realtime);

/**
 * Releases the connectivity handle. Clients created with it keep their own reference.
 */
void qortoo_local_connectivity_free(struct QortooLocalConnectivity *conn);

/**
 * Releases a string returned by this library (or set into a `QortooError`).
 */
void qortoo_string_free(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* QORTOO_FFI_H */
