/* Auto-generated by cbindgen from qortoo-ffi. Do not edit manually. */

#ifndef QORTOO_FFI_H
#define QORTOO_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Error code used when a panic crosses the FFI boundary or an error variant is unknown.
 */
#define QORTOO_ERR_INTERNAL_FFI 999

/**
 * Error code used when an argument (null pointer, invalid UTF-8) is rejected at the boundary.
 */
#define QORTOO_ERR_INVALID_ARGUMENT 998

/**
 * `qortoo_observability_init` was already called in this process.
 */
#define QORTOO_ERR_OBSERVABILITY_ALREADY_INITIALIZED 900

/**
 * `qortoo_observability_init` was called after `qortoo_observability_shutdown`.
 */
#define QORTOO_ERR_OBSERVABILITY_SHUT_DOWN 901

/**
 * The global `tracing` subscriber is owned by someone else in this process.
 */
#define QORTOO_ERR_OBSERVABILITY_SUBSCRIBER 902

/**
 * A telemetry exporter failed to start, flush, or stop.
 */
#define QORTOO_ERR_OBSERVABILITY_EXPORTER 903

/**
 * The global `metrics` recorder is owned by someone else in this process.
 */
#define QORTOO_ERR_OBSERVABILITY_RECORDER 904

/**
 * The observability options do not describe a valid configuration.
 */
#define QORTOO_ERR_OBSERVABILITY_INVALID_CONFIG 905

/**
 * A previous initialization installed an irreversible global before a later step failed.
 */
#define QORTOO_ERR_OBSERVABILITY_PARTIALLY_INITIALIZED 906

/**
 * ABI major version this build implements. Bump on any breaking change to exported
 * symbols, struct layout, or calling convention.
 */
#define QORTOO_ABI_VERSION_MAJOR 1

/**
 * ABI minor version this build implements. Bump when symbols are added without
 * breaking existing ones; reset to 0 when the major version bumps.
 *
 * - 0: the shared `QortooDatatype` handle. Operations whose signature does not name
 *   a datatype — synchronization, metadata, handlers — are exported once as
 *   `qortoo_datatype_*` and reached through `qortoo_<type>_as_datatype`, replacing
 *   the per-type copy of each.
 */
#define QORTOO_ABI_VERSION_MINOR 0

/**
 * Opaque handle to a `qortoo::Client`.
 */
typedef struct QortooClient QortooClient;

/**
 * Opaque handle to a `qortoo::Counter`. Cheap to clone on the Rust side; every handle
 * shares the same underlying datatype.
 */
typedef struct QortooCounter QortooCounter;

/**
 * Opaque handle to any datatype, carrying what they all have in common.
 *
 * Every concrete handle (`QortooCounter`, `QortooVariable`) holds one of these, and
 * `qortoo_<type>_as_datatype` borrows it. That borrow is a reference to a field of
 * the concrete handle, not a second handle: it stays valid for exactly as long as
 * the concrete handle, which is what `qortoo_<type>_free` releases.
 */
typedef struct QortooDatatype QortooDatatype;

/**
 * Opaque handle to a `qortoo::LocalConnectivity`. The same handle may be passed to
 * several `qortoo_client_new` calls to share one in-memory backend.
 */
typedef struct QortooLocalConnectivity QortooLocalConnectivity;

/**
 * Opaque handle to a `qortoo::Variable`. Cheap to clone on the Rust side; every handle
 * shares the same underlying datatype.
 */
typedef struct QortooVariable QortooVariable;

/**
 * Out-parameter carrying the result of a fallible call.
 */
typedef struct QortooError {
  /**
   * 0 on success; otherwise the Rust error discriminant (or 998/999, see constants).
   */
  int32_t code;
  /**
   * Human-readable message, or null. Release with `qortoo_string_free`.
   */
  char *msg;
} QortooError;

/**
 * State-change notification: `(userdata, old_state, new_state)` with `DatatypeState`
 * discriminants. Invoked on a Qortoo tokio worker thread.
 */
typedef void (*QortooOnStateChangeCallback)(uintptr_t userdata, int32_t old_state, int32_t new_state);

/**
 * Error notification: `(userdata, error_code, error_msg)`. `error_msg` is only valid
 * during the call. Invoked on a Qortoo tokio worker thread.
 */
typedef void (*QortooOnErrorCallback)(uintptr_t userdata, int32_t code, const char *msg);

/**
 * Called exactly once when the handler owning `userdata` is dropped, so the foreign
 * side can release resources tied to it (e.g., a Go `cgo.Handle`).
 */
typedef void (*QortooUserdataDropCallback)(uintptr_t userdata);

/**
 * Options applied when building a datatype. A zeroed struct (or a null pointer where
 * the options parameter is nullable) selects the defaults.
 */
typedef struct QortooDatatypeOptions {
  /**
   * Marks the datatype read-only (`DatatypeBuilder::with_readonly`).
   */
  bool readonly;
  /**
   * Max push-buffer size in bytes; 0 keeps the SDK default (clamped by the SDK).
   */
  uint64_t max_push_buffer_size;
  /**
   * Priority of the handler registered from the fields below (lower runs first).
   */
  uintptr_t handler_priority;
  /**
   * Optional state-change callback; null to skip.
   */
  QortooOnStateChangeCallback on_state_change;
  /**
   * Optional error callback; null to skip.
   */
  QortooOnErrorCallback on_error;
  /**
   * Opaque integer (e.g., a Go `cgo.Handle`) forwarded to both callbacks.
   */
  uintptr_t handler_userdata;
  /**
   * Optional destructor for `handler_userdata`; null to skip.
   */
  QortooUserdataDropCallback handler_userdata_drop;
} QortooDatatypeOptions;

/**
 * Transaction body. Receives a transaction-scoped counter (owned by Rust — do NOT free)
 * and the userdata given to `qortoo_counter_transaction`. Return 0 to commit, non-zero
 * to roll back.
 */
typedef int32_t (*QortooTxCallback)(struct QortooCounter *tx_counter, uintptr_t userdata);

/**
 * Observability configuration. Every string is nullable; a null selects the default
 * described on the field. A zeroed struct installs nothing but is still valid.
 */
typedef struct QortooObservabilityOptions {
  /**
   * `service.name` reported to the trace backend. Null uses `"qortoo"`; set it to the
   * same value the application uses for its own telemetry.
   */
  const char *service_name;
  /**
   * Language of the binding, exported as `qortoo.binding.language` (e.g. `"go"`).
   * Null omits the attribute.
   */
  const char *binding_language;
  /**
   * `tracing` filter directives (e.g. `"qortoo=debug"`). Null falls back to `RUST_LOG`,
   * then to `"qortoo=info"`.
   */
  const char *log_filter;
  /**
   * Stdout log format: 0 = off, 1 = JSON, 2 = Qortoo's compact text format.
   * Text colors are enabled only when stdout is connected to a terminal.
   */
  int32_t log_format;
  /**
   * Exports spans over OTLP/gRPC.
   */
  bool trace_enabled;
  /**
   * OTLP endpoint. Null falls back to `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT`, then
   * `OTEL_EXPORTER_OTLP_ENDPOINT`, then `http://localhost:4317`.
   */
  const char *otlp_endpoint;
  /**
   * Installs the `metrics` recorder and serves a Prometheus scrape endpoint.
   */
  bool metrics_enabled;
  /**
   * Address of that endpoint. Null uses `0.0.0.0:9000`.
   */
  const char *metrics_listen_addr;
} QortooObservabilityOptions;

/**
 * Caller-owned byte buffer returned by this library (e.g. a JSON payload). Release it
 * exactly once with `qortoo_owned_bytes_free`.
 *
 * `{data: null, len: 0}` is the "no buffer" sentinel that an output parameter holds
 * until the call succeeds; freeing it is a no-op. A successful call replaces it with a
 * non-empty buffer.
 */
typedef struct QortooOwnedBytes {
  /**
   * Start of the buffer, or null for the empty sentinel.
   */
  uint8_t *data;
  /**
   * Length of the buffer in bytes.
   */
  uintptr_t len;
} QortooOwnedBytes;

/**
 * Transaction body. Receives a transaction-scoped variable (owned by Rust — do NOT
 * free) and the userdata given to `qortoo_variable_transaction`. Return 0 to commit,
 * non-zero to roll back.
 */
typedef int32_t (*QortooVariableTxCallback)(struct QortooVariable *tx_variable, uintptr_t userdata);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates a client. `connectivity` may be null (no-op backend).
 * Returns null on error (see `err_out`). Release with `qortoo_client_free`.
 */
struct QortooClient *qortoo_client_new(const char *collection,
                                       const char *alias,
                                       const struct QortooLocalConnectivity *connectivity,
                                       struct QortooError *err_out);

/**
 * Releases the client. Datatypes built from it stay valid until their own free.
 */
void qortoo_client_free(struct QortooClient *client);

/**
 * Returns the collection name (release with `qortoo_string_free`).
 */
char *qortoo_client_get_collection(const struct QortooClient *client);

/**
 * Returns the client alias (release with `qortoo_string_free`).
 */
char *qortoo_client_get_alias(const struct QortooClient *client);

/**
 * Marks the datatype identified by `key` as unsubscribing. With manual connectivity a
 * following `qortoo_datatype_sync` drives it to Disabled.
 */
void qortoo_client_unsubscribe_datatype(const struct QortooClient *client,
                                        const char *key,
                                        struct QortooError *err_out);

/**
 * Builds a counter in `Creating` state (writable). `options` may be null.
 * The handler `userdata_drop` (if provided) fires exactly once even on failure.
 */
struct QortooCounter *qortoo_counter_create(const struct QortooClient *client,
                                            const char *key,
                                            const struct QortooDatatypeOptions *options,
                                            struct QortooError *err_out);

/**
 * Builds a counter in `Subscribing` state (read-only until synced). `options` may be null.
 * The handler `userdata_drop` (if provided) fires exactly once even on failure.
 */
struct QortooCounter *qortoo_counter_subscribe(const struct QortooClient *client,
                                               const char *key,
                                               const struct QortooDatatypeOptions *options,
                                               struct QortooError *err_out);

/**
 * Builds a counter in `SubscribingOrCreating` state (writable). `options` may be null.
 * The handler `userdata_drop` (if provided) fires exactly once even on failure.
 */
struct QortooCounter *qortoo_counter_subscribe_or_create(const struct QortooClient *client,
                                                         const char *key,
                                                         const struct QortooDatatypeOptions *options,
                                                         struct QortooError *err_out);

/**
 * Releases this counter handle; the underlying datatype lives on inside the client.
 * Any shared handle obtained from `qortoo_counter_as_datatype` dies with it.
 */
void qortoo_counter_free(struct QortooCounter *counter);

/**
 * Returns this counter as the shared handle the `qortoo_datatype_*` entry points
 * take — those cover synchronization, metadata, and handlers.
 *
 * The result borrows `counter`: it is a pointer to a field of the counter handle, valid
 * for exactly as long as that handle. It is not a second handle and is never released
 * on its own — `qortoo_counter_free` releases the allocation exactly once, and this
 * pointer dies with it.
 */
const struct QortooDatatype *qortoo_counter_as_datatype(const struct QortooCounter *counter);

/**
 * Increases the counter by `delta` (may be negative). Returns the new value, or 0 on error.
 */
int64_t qortoo_counter_increase_by(const struct QortooCounter *counter,
                                   int64_t delta,
                                   struct QortooError *err_out);

/**
 * Increases the counter by 1. Returns the new value, or 0 on error.
 */
int64_t qortoo_counter_increase(const struct QortooCounter *counter, struct QortooError *err_out);

/**
 * Returns the current counter value (0 if `counter` is null).
 */
int64_t qortoo_counter_get_value(const struct QortooCounter *counter);

/**
 * Executes `callback` atomically. The callback runs inline on the calling thread with a
 * transaction-scoped counter handle owned by Rust (do NOT free it, do NOT keep it after
 * returning). A non-zero return rolls back every operation performed inside.
 */
void qortoo_counter_transaction(const struct QortooCounter *counter,
                                const char *tag,
                                QortooTxCallback callback,
                                uintptr_t userdata,
                                struct QortooError *err_out);

/**
 * `qortoo_counter_transaction` continuing the caller's trace.
 *
 * `traceparent`/`tracestate` carry the W3C trace context of the calling span (both
 * nullable); the commit and any sync it triggers become children of that span.
 *
 * This is a separate entry point rather than an extension of
 * `qortoo_counter_transaction` so a caller that does not propagate context pays for
 * none of it.
 */
void qortoo_counter_transaction_with_context(const struct QortooCounter *counter,
                                             const char *tag,
                                             const char *traceparent,
                                             const char *tracestate,
                                             QortooTxCallback callback,
                                             uintptr_t userdata,
                                             struct QortooError *err_out);

/**
 * Returns the `DatatypeState` discriminant, or -1 if `datatype` is null.
 */
int32_t qortoo_datatype_get_state(const struct QortooDatatype *datatype);

/**
 * Returns the `DataType` discriminant, or -1 if `datatype` is null.
 */
int32_t qortoo_datatype_get_type(const struct QortooDatatype *datatype);

/**
 * Returns the datatype key (release with `qortoo_string_free`), or null if
 * `datatype` is null.
 */
char *qortoo_datatype_get_key(const struct QortooDatatype *datatype);

/**
 * Returns the server-side version (0 before the first sync or if `datatype` is null).
 */
uint64_t qortoo_datatype_get_server_version(const struct QortooDatatype *datatype);

/**
 * Returns the client-side version (number of local operations).
 */
uint64_t qortoo_datatype_get_client_version(const struct QortooDatatype *datatype);

/**
 * Returns the last synchronized client version.
 */
uint64_t qortoo_datatype_get_synced_client_version(const struct QortooDatatype *datatype);

/**
 * Blocking push/pull synchronization with the connectivity backend.
 */
void qortoo_datatype_sync(const struct QortooDatatype *datatype, struct QortooError *err_out);

/**
 * `qortoo_datatype_sync` continuing the caller's trace via the W3C
 * `traceparent`/`tracestate` headers (both nullable; absent or malformed headers
 * fall back to no parent).
 */
void qortoo_datatype_sync_with_context(const struct QortooDatatype *datatype,
                                       const char *traceparent,
                                       const char *tracestate,
                                       struct QortooError *err_out);

/**
 * Marks this datatype as unsubscribing (see `qortoo_client_unsubscribe_datatype`).
 */
void qortoo_datatype_unsubscribe(const struct QortooDatatype *datatype,
                                 struct QortooError *err_out);

/**
 * Registers (or replaces) a handler at `priority`. Callbacks arrive on Qortoo tokio
 * worker threads; `userdata_drop` fires exactly once when the handler is replaced or
 * unset — or immediately if `datatype` is null and the handler cannot be registered.
 */
void qortoo_datatype_set_handler(const struct QortooDatatype *datatype,
                                 uintptr_t priority,
                                 QortooOnStateChangeCallback on_state_change,
                                 QortooOnErrorCallback on_error,
                                 uintptr_t userdata,
                                 QortooUserdataDropCallback userdata_drop);

/**
 * Removes the handler at `priority`. Returns true if one was removed.
 */
bool qortoo_datatype_unset_handler(const struct QortooDatatype *datatype, uintptr_t priority);

/**
 * Creates an in-memory connectivity backend (realtime mode by default).
 */
struct QortooLocalConnectivity *qortoo_local_connectivity_new(void);

/**
 * Switches between realtime (true) and manual (false) synchronization.
 */
void qortoo_local_connectivity_set_realtime(struct QortooLocalConnectivity *conn, bool realtime);

/**
 * Releases the connectivity handle. Clients created with it keep their own reference.
 */
void qortoo_local_connectivity_free(struct QortooLocalConnectivity *conn);

/**
 * Installs the logging, tracing, and metrics pipelines described by `options`
 * (null selects every default). Call it once per process, before creating clients.
 *
 * Fails with a distinct code when it is called twice, when it is called after
 * `qortoo_observability_shutdown`, when another library already owns the global
 * subscriber or recorder, when an exporter cannot start, or when the options are
 * invalid — the application must not silently lose the telemetry it configured.
 */
void qortoo_observability_init(const struct QortooObservabilityOptions *options,
                               struct QortooError *err_out);

/**
 * Flushes pending telemetry and stops the exporters, waiting at most `timeout_ms`
 * (0 selects 5s). A no-op when nothing was initialized, so it is always safe to defer.
 *
 * This is terminal: `tracing` allows one global subscriber per process, so a later
 * `qortoo_observability_init` fails instead of pretending to restore the pipelines.
 * Call it after every `qortoo_client_free`, and before the application shuts its own
 * telemetry down.
 */
void qortoo_observability_shutdown(uint64_t timeout_ms, struct QortooError *err_out);

/**
 * Releases a byte buffer produced by this library. Passing the `{null, 0}` sentinel is
 * a no-op; every other value must have come from this library and must not be freed
 * twice.
 */
void qortoo_owned_bytes_free(struct QortooOwnedBytes value);

/**
 * Releases a string returned by this library (or set into a `QortooError`).
 */
void qortoo_string_free(char *s);

/**
 * Builds a variable in `Creating` state (writable). `options` may be null.
 * The handler `userdata_drop` (if provided) fires exactly once even on failure.
 */
struct QortooVariable *qortoo_variable_create(const struct QortooClient *client,
                                              const char *key,
                                              const struct QortooDatatypeOptions *options,
                                              struct QortooError *err_out);

/**
 * Builds a variable in `Subscribing` state (read-only until synced). `options` may be null.
 * The handler `userdata_drop` (if provided) fires exactly once even on failure.
 */
struct QortooVariable *qortoo_variable_subscribe(const struct QortooClient *client,
                                                 const char *key,
                                                 const struct QortooDatatypeOptions *options,
                                                 struct QortooError *err_out);

/**
 * Builds a variable in `SubscribingOrCreating` state (writable). `options` may be null.
 * The handler `userdata_drop` (if provided) fires exactly once even on failure.
 */
struct QortooVariable *qortoo_variable_subscribe_or_create(const struct QortooClient *client,
                                                           const char *key,
                                                           const struct QortooDatatypeOptions *options,
                                                           struct QortooError *err_out);

/**
 * Releases this variable handle; the underlying datatype lives on inside the client.
 * Any shared handle obtained from `qortoo_variable_as_datatype` dies with it.
 */
void qortoo_variable_free(struct QortooVariable *variable);

/**
 * Returns this variable as the shared handle the `qortoo_datatype_*` entry points
 * take — those cover synchronization, metadata, and handlers.
 *
 * The result borrows `variable`: it is a pointer to a field of the variable handle, valid
 * for exactly as long as that handle. It is not a second handle and is never released
 * on its own — `qortoo_variable_free` releases the allocation exactly once, and this
 * pointer dies with it.
 */
const struct QortooDatatype *qortoo_variable_as_datatype(const struct QortooVariable *variable);

/**
 * Sets the variable to the JSON value in `len` bytes at `data` — exactly one UTF-8
 * JSON value, stored verbatim (never reparsed or reordered; see
 * `qortoo_variable_get_raw`).
 *
 * On success `previous_out` receives the value the variable held just before this set
 * as a caller-owned buffer (`"null"` for the first set), to be released once with
 * `qortoo_owned_bytes_free`. On any error the variable is left unchanged and
 * `previous_out` stays `{NULL, 0}`.
 *
 * Rejects a null `variable`/`data`/`previous_out` (`QORTOO_ERR_INVALID_ARGUMENT`) and
 * input that is not exactly one UTF-8 JSON value (code 214).
 */
void qortoo_variable_set_raw(const struct QortooVariable *variable,
                             const uint8_t *data,
                             uintptr_t len,
                             struct QortooOwnedBytes *previous_out,
                             struct QortooError *err_out);

/**
 * Writes the current value to `value_out` as a caller-owned buffer holding the stored
 * JSON bytes verbatim (`"null"` for the initial value); release it once with
 * `qortoo_owned_bytes_free`. On any error `value_out` stays `{NULL, 0}`.
 *
 * Rejects a null `variable` or `value_out` (`QORTOO_ERR_INVALID_ARGUMENT`).
 */
void qortoo_variable_get_raw(const struct QortooVariable *variable,
                             struct QortooOwnedBytes *value_out,
                             struct QortooError *err_out);

/**
 * Executes `callback` atomically. The callback runs inline on the calling thread with a
 * transaction-scoped variable handle owned by Rust (do NOT free it, do NOT keep it
 * after returning). A non-zero return rolls back every operation performed inside.
 */
void qortoo_variable_transaction(const struct QortooVariable *variable,
                                 const char *tag,
                                 QortooVariableTxCallback callback,
                                 uintptr_t userdata,
                                 struct QortooError *err_out);

/**
 * `qortoo_variable_transaction` continuing the caller's trace.
 *
 * `traceparent`/`tracestate` carry the W3C trace context of the calling span (both
 * nullable); the commit and any sync it triggers become children of that span.
 *
 * This is a separate entry point rather than an extension of
 * `qortoo_variable_transaction` so a caller that does not propagate context pays for
 * none of it.
 */
void qortoo_variable_transaction_with_context(const struct QortooVariable *variable,
                                              const char *tag,
                                              const char *traceparent,
                                              const char *tracestate,
                                              QortooVariableTxCallback callback,
                                              uintptr_t userdata,
                                              struct QortooError *err_out);

/**
 * Returns the ABI major version this library implements. Compare against the value
 * the binding was generated for before making any other call into this library.
 */
uint32_t qortoo_abi_version_major(void);

/**
 * Returns the ABI minor version this library implements.
 */
uint32_t qortoo_abi_version_minor(void);

/**
 * Returns this crate's SDK version (`CARGO_PKG_VERSION`, e.g. `"0.1.0"`). Distinct
 * from the ABI version: the SDK version can advance without an ABI break. Release the
 * returned string with `qortoo_string_free`.
 */
char *qortoo_sdk_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* QORTOO_FFI_H */
