fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();

    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        header: Some(
            "/* Auto-generated by cbindgen from qortoo-ffi. Do not edit manually. */".into(),
        ),
        include_guard: Some("QORTOO_FFI_H".into()),
        cpp_compat: true,
        documentation: true,
        ..Default::default()
    };

    cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .generate()
        .expect("failed to generate C header with cbindgen")
        .write_to_file(format!("{crate_dir}/include/qortoo.h"));

    println!("cargo:rerun-if-changed=src");
}
